services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/library
      - PORT=4000
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./doc:/app/doc
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
    networks:
      - library-network
    depends_on:
      - db
    restart: always
    command: nest start --watch

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-network
    restart: always

networks:
  library-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs:
