services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
      - '${PORT_PRISMA}:${PORT_PRISMA}'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SECRET_REFRESH_KEY=${JWT_SECRET_REFRESH_KEY}
      - PORT=${PORT}
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./prisma:/app/prisma
      - ./logs:/app/logs
      - ./doc:/app/doc
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./nest-cli.json:/app/nest-cli.json
    networks:
      - library-network
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! pg_isready -h db -p 5432 -U ${POSTGRES_USER}; do
          sleep 1
        done &&
        echo 'Database is ready!' &&
        npm install @nestjs/passport passport passport-jwt bcrypt @types/passport-jwt @types/bcrypt &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:dev
      "
    image: seygorin/nodejs2024q3:latest

networks:
  library-network:
    driver: bridge

volumes:
  postgres_data:
  app_logs:
